apiVersion: v1
kind: Service
metadata:
  name: football-intro-app-metrics
  namespace: default
  labels:
    app: football-intro-app
spec:
  type: ClusterIP
  selector:
    app: football-intro-app
  ports:
  - name: metrics
    port: 9113
    targetPort: 9113
    protocol: TCP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: football-intro-app-monitor
  namespace: monitoring
  labels:
    app: football-intro-app
    release: prometheus
spec:
  selector:
    matchLabels:
      app: football-intro-app
  namespaceSelector:
    matchNames:
    - default
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics